services:
 application:
  build:
   context: .
  depends_on:
   - db
  ports:
   - "8000:8000"
 db:
  image: postgres
  environment:
   POSTGRES_USER: redirect
   POSTGRES_PASSWORD: redirect
   POSTGRES_DB: redirect
